# Generated by Django 4.2.3 on 2023-07-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kassa', '0002_delete_operationnameminus_operationname_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationname',
            name='type',
            field=models.CharField(choices=[('plus', 'Plus'), ('minus', 'Minus')], default='plus', max_length=5),
        ),
        migrations.AlterField(
            model_name='sale',
            name='user',
            field=models.CharField(default='admin', max_length=32),
        ),
    ]
